# Generated by Django 3.2.8 on 2021-12-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(blank=True, max_length=50)),
                ('playerPosition', models.CharField(blank=True, max_length=20)),
                ('UserPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football.userplayer')),
            ],
        ),
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('UserPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football.userplayer')),
            ],
        ),
    ]
