# Generated by Django 3.2.8 on 2021-12-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0002_injuryreport_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('UserPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football.userplayer')),
            ],
        ),
    ]
