# Generated by Django 3.2.8 on 2021-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0003_commentboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryreport',
            name='playerTeam',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
