# Generated by Django 3.2.8 on 2021-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0005_auto_20211206_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentboard',
            name='comment',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
