# Generated by Django 3.2.8 on 2021-12-06 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy_football', '0006_alter_commentboard_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentboard',
            name='UserPlayer',
        ),
        migrations.AddField(
            model_name='commentboard',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentboard',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
