# Generated by Django 3.2.8 on 2021-12-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0007_auto_20211206_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='UserPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy_football.userplayer'),
        ),
    ]
