# Generated by Django 3.2.8 on 2021-12-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0009_auto_20211209_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentboard',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='userplayer',
            old_name='user',
            new_name='userId',
        ),
    ]
