# Generated by Django 3.2.8 on 2021-12-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0010_auto_20211209_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='userPlayer',
            new_name='userPlayerId',
        ),
        migrations.AddField(
            model_name='team',
            name='favoriteStatus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
