# Generated by Django 3.2.8 on 2021-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football', '0011_auto_20211212_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(blank=True, max_length=200)),
                ('searchTerm', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
